#!/usr/bin/env python3
"""The asks ledger: docs/asks.md from docs/asks.toml, every ask the
sibling repositories filed with its state here, each repro run against
this build (target/release/xetal).

    scripts/asks.py                 # write docs/asks.md
    scripts/asks.py --check         # fail if docs/asks.md is stale, or
                                    # a landed ask's repro fails
    scripts/asks.py --siblings DIR  # compare with DIR/X_eTaL-*/docs/xetal-asks.md

A landed ask's repro must pass. A planned, declined or new ask whose
repro passes is flagged in the ledger: it may have landed.
"""

import re
import subprocess
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "docs/asks.toml"
OUT = ROOT / "docs/asks.md"
XETAL = ROOT / "target/release/xetal"
WORK = ROOT / "work/asks"
REPOS = ["X_eTaL-demos", "X_eTaL-ML", "X_eTaL-games", "X_eTaL-libraries", "X_eTaL-extensions"]
STATES = ["landed", "partly landed", "planned", "declined", "new"]


def asks():
    return tomllib.loads(DATA.read_text())["ask"]


def notices():
    """Changes here every sibling repository should act on, each a
    [[notice]] with a title and its text (paragraphs split by blank lines)."""
    return tomllib.loads(DATA.read_text()).get("notice", [])


def outcome(ask):
    """What this build says about the ask: "passes", "fails", a golden,
    or "-" when it has no repro (a speed or build-time ask)."""
    if "golden" in ask:
        return f"golden `{ask['golden']}`"
    if "repro" not in ask:
        return "-"
    WORK.mkdir(parents=True, exist_ok=True)
    path = WORK / f"{ask['id']}.xtl"
    path.write_text(ask["repro"] + "\n")
    run = subprocess.run([str(XETAL), "run", str(path)], capture_output=True,
                         text=True, timeout=60, cwd=ROOT)
    out, works = run.stdout + run.stderr, ask.get("works", "")
    if works.startswith("error["):
        met = works in out
    else:
        lines = [line.strip() for line in out.splitlines()]
        met = "error[" not in out and (works in lines if works else run.returncode == 0)
    return "passes" if met else "fails"


def flags(ask, result):
    """A disagreement between the state and the repro, or None."""
    if ask["state"] == "landed" and result == "fails":
        return f"{ask['id']}: landed, but its repro fails"
    if ask["state"] in ("planned", "declined", "new") and result == "passes":
        return f"{ask['id']}: {ask['state']}, but its repro passes (landed?)"
    return None


def render(rows):
    out = [
        "# Asks: what the sibling repositories asked of X_eTaL",
        "",
        "Generated by `scripts/asks.py` from `docs/asks.toml`, with each",
        "ask's repro run against this build (`just asks` regenerates it, the",
        "gate checks it). The asks are filed in each repository's",
        "`docs/xetal-asks.md`; this ledger says where each stands here:",
        "**landed** (with the commit), **partly landed**, **planned** (with",
        "the saga or step in `docs/plan.md`), **declined** (with the",
        "reason), or **new** (not yet triaged). A repro **passes** when this",
        "build already does what the ask wants.",
        "",
        *summary(rows),
    ]
    for n in notices():
        out += [f"## Notice: {n['title']}", "", n["text"].strip(), ""]
    raised = [f for _, _, f in rows if f]
    if raised:
        out += ["## To look at", ""] + [f"- {f}" for f in raised] + [""]
    for repo in REPOS:
        mine = [(a, r) for a, r, _ in rows if a["repo"] == repo]
        out += [f"## {repo}", "", "| # | Ask | State | Here | Repro |",
                "| - | --- | ----- | ---- | ----- |"]
        out += [f"| {a['id']} | {a['ask']} | {a['state']} | {a['here']} | {r} |"
                for a, r in mine]
        out.append("")
    return "\n".join(out).rstrip("\n") + "\n"


def summary(rows):
    head = "| Repository | " + " | ".join(s.capitalize() for s in STATES) + " |"
    rule = "| ---------- | " + " | ".join("-" * len(s) for s in STATES) + " |"
    lines = ["## Summary", "", head, rule]
    for repo in REPOS + ["All"]:
        mine = [a for a, _, _ in rows if repo in ("All", a["repo"])]
        counts = [str(sum(a["state"] == s for a in mine)) for s in STATES]
        lines.append(f"| {repo} | " + " | ".join(counts) + " |")
    return lines + [""]


def siblings(top):
    """Each sibling's count of filed asks (rows of its first table)
    against the ledger's, to catch asks filed since."""
    ledger = asks()
    for repo in REPOS:
        path = Path(top) / repo / "docs/xetal-asks.md"
        if not path.exists():
            print(f"{repo}: no docs/xetal-asks.md under {top}")
            continue
        rows = first_table(path.read_text())
        here = sum(a["repo"] == repo for a in ledger)
        mark = "" if rows == here else "   <- differs: update docs/asks.toml"
        print(f"{repo}: {rows} filed, {here} in the ledger{mark}")


def first_table(text):
    """The number of data rows in the first markdown table."""
    lines, started = [], False
    for line in text.splitlines():
        if line.startswith("|"):
            started = True
            lines.append(line)
        elif started:
            break
    return sum(1 for l in lines[2:] if re.sub(r"[|\s]", "", l))


def main():
    args = sys.argv[1:]
    if args[:1] == ["--siblings"] and len(args) == 2:
        siblings(args[1])
        return
    rows = []
    for ask in asks():
        if ask["state"] not in STATES:
            sys.exit(f"asks: {ask['id']} has an unknown state {ask['state']!r}")
        result = outcome(ask)
        rows.append((ask, result, flags(ask, result)))
    text = render(rows)
    broken = [f for a, _, f in rows if f and a["state"] == "landed"]
    if "--check" in args:
        if broken:
            sys.exit("asks: " + "; ".join(broken))
        if not OUT.exists() or OUT.read_text() != text:
            sys.exit("asks: docs/asks.md is not current (run scripts/asks.py, or just asks)")
        print("asks: docs/asks.md is current")
        return
    OUT.write_text(text)
    print(OUT.relative_to(ROOT))


if __name__ == "__main__":
    main()
